sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge group.sem
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network group.sem mongo
  - docker build -t se_methods .
  - docker run --network se-methods se_methods