language: java
addons:
  hosts:
  - db
services:
- docker
install:
- docker build -t database db/.
- docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- mvn clean
jobs:
  include:
  - stage: unit tests
    install: skip
    jdk: oraclejdk11
    script: mvn test -Dtest=com.group.sem.AppTests
  - stage: integreation tests
    jdk: oraclejdk11
    script: mvn test -Dtest=com.group.sem.AppIntegrationTest
  - stage: GitHub Release
    install: skip
    jdk: oraclejdk11
    script:
    - echo "Deploying to GitHub Releases"
    - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
    before_deploy:
    - git config --local user.name "Tom McEachan"
    - git config --local user.email "tom.a.mceachan@outlook.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-(date +'%Y-%m-%d')-$(git log --format=%h -1)}
    - git tage $Travis_TAG
    deploy:
      provider: releases
      api-key: "$GITHUB_OATH_TOKEN"
      file: "$TRAVIS_BUILD_DIR/target/groupHSemMethods.jar"
      cleanup: false
stages:
- unit tests
- integration tests
- name: deploy
  if: branch = master
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d
