sudo: false
language: java

addons:
  hosts:
    -db

services:
  - docker

install:
  -docker build -t database db/.
  -docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306
  -mvn install -DskipTests=true - Dmaven.javadoc.skip=true -B -V

before_script:
    -mvn clean

script:
    -mvn test -Dtest=com.group.sem.AppTest