dist: xenial
os: linux

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge group-h-sem
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network group-h-sem mongo
  - docker build -t group-h-sem .
  - docker run --network group-h-sem group-h-sem