@startuml
'https://plantuml.com/use-case-diagram

    'This represents use-case 1'
    actor Marketing as "Marketing Manager"
    rectangle Database
    usecase UCa as "Print Queried Data"
    usecase UC1 as "Get countries from continent,
                    sorted by largest
                    pop to smallest"
    top to bottom direction
    Marketing -> UC1
    UC1 ..> UCa : include
    UC1 <- Database

    'This represents use-case 2'
    actor Logistics as "Global Logistics Manager"
    rectangle Database
    usecase UCa as "Print Queried Data"
    usecase UC2 as "Produce a report of all
                    countries in the world"
     top to bottom direction
     Logistics -> UC2
     UC2 ..> UCa : include
     UC2 <- Database


    'This represents use-case 3'
    actor Finance as    "Regional Finance Manager"
    rectangle Database
    usecase UCa as "Print Queried Data"
    usecase UC3 as "Produce a report of all
                    countries in a region"
    top to bottom direction
    Finance -> UC3
    UC3 ..> UCa :include
    UC3 <- Database


    'This represents use-case 4'

    actor Finance as "Global Finance Manager"
    rectangle Database
    usecase UCa as "Print Queried Data"
    usecase UC4 as "Produce report of the top N
                    populated countries in the world"
    top to bottom direction
    Finance -> UC4
    UC4 ..> UCa : include
    UC4 <- Database


    'This represents use-case 5'
    actor Finance as "Continental Finance Manager"
    rectangle Database
    usecase UCa as "Print Queried Data"
    usecase UC5 as "Produce a report of the top N
                 populated countries in a continent"
    top to bottom direction
    Finance -> UC5
    UC5 ..> UCa : include
    UC5 <- Database

    'This represents use-case 6'
        actor Logistics as "Regional Logistics Manager"
        rectangle Database
        usecase UCa as "Print Queried Data"
        usecase UC6 as "Produce a report of the top N
                     populated countries in a region"
        top to bottom direction
        Logistics -> UC6
        UC6 ..> UCa : include
        UC6 <- Database


    'This represents use-case 7'

        actor Logistics as "District Level Logistics Manager"
        rectangle Database
        usecase UCa as "Print Queried Data"
        usecase UC7 as "Produce a report of all the
                        cities in a district"
        top to bottom direction
        Logistics -> UC7
        UC7 ..> UCa : include
        UC7 <- Database

    'This represents use-case 8'

       actor Logistics as "Global Level Logistics Manager"
       rectangle Database
       usecase UCa as "Print Queried Data"
       usecase UC8 as "Produce a report of all the
                       cities in the world"
       top to bottom direction
       Logistics -> UC8
       UC8 ..> UCa : include
       UC8 <- Database



     'This represents use-case 9'
      actor Logistics as "Continental Logistics Manager"
      rectangle Database
      usecase UCa as "Print Queried Data"
      usecase UC9 as "Produce a report of all cities in
                      a specified continent from
                      largest to smallest"
      top to bottom direction
      Logistics -> UC9
      UC9 ..> UCa : include
      UC9<- Database


@enduml